name: snapscrub
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - opencv
  - pytorch
  - torchvision
  - tensorflow
  - scikit-image
  - jupyterlab
  - tqdm
  - pip
  - pyheif
  - pillow-heif
  - imagehash
  - pip:
      - torch
      - transformers
      - pillow
      - git+https://github.com/openai/CLIP.git