name: snapscrub
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - opencv
  - pytorch
  - torchvision
  - tensorflow
  - scikit-image
  - jupyterlab
  - tqdm
  - pip
  - pip:
      - torch
      - transformers
      - pillow