name: snapscrub
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - opencv
  - pillow
  - scikit-image
  - tensorflow
  - pytorch
  - torchvision
  - torchaudio
  - imagehash
  - pip
  - pip:
      - ftfy
      - regex
      - tqdm
      - pillow-heif