name: snapscrub
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.26.2
  - pandas=2.1.3
  - scikit-image=0.22.0
  - opencv=4.8.1
  - tqdm=4.66.1
  - pytest=7.4.3
  - jupyterlab=4.0.9
  - pytorch=2.1.0
  - torchvision=0.15.2
  - pip=23.3.1
  - pip:
      - tensorflow-macos==2.14.0
      - tensorflow-metal==1.1.0
      - opencv-python-headless==4.8.1.78
      - transformers==4.36.2
      - clip-by-openai==1.0.1